exclude: "docs|node_modules|migrations|.git|.tox|.yaml"
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude_types: ["plain-text"]
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
        additional_dependencies: ["click==8.0.4"]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort
